[package]
name = "coopserver"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = { version = "0.4.2", default-features = false, features = ["proc_macro"] }
retour = "0.3.1"
